In [47]:
#text procssing using various NLP algorithms
import pandas as pd
import numpy as np
import nltk
import string
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import *
from sklearn.metrics import roc_curve, auc
from nltk.stem.porter import PorterStemmer

import re
# Tutorial about Python regular expressions: https://pymotw.com/2/re/
import string
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer

#from gensim.models import Word2Vec
#from gensim.models import KeyedVectors
import pickle

from tqdm import tqdm
import os

In [48]:
#constructing text_array for testing purpose
text_array = []
string_1 = 'science and technology are strongly related things and important things too in life'
string_2 = 'Technology enables humans to simplify life'
string_3 = 'there is more to life than just eating and sleeping'
string_4 = 'life is what you make it to be'
text_array.append(string_1)
text_array.append(string_2)
text_array.append(string_3)
text_array.append(string_4)
print(text_array)


['science and technology are strongly related things and important things too in life', 'Technology enables humans to simplify life', 'there is more to life than just eating and sleeping', 'life is what you make it to be']


# Ragular bag of words

In [49]:
count_vect = CountVectorizer()
count_vect.fit(text_array)
print("some feature names ", count_vect.get_feature_names())
print('='*50)
final_counts = count_vect.transform(text_array)
print(type(final_counts))
print(final_counts.shape)
print(final_counts[0])
print(final_counts.toarray())



some feature names  ['and', 'are', 'be', 'eating', 'enables', 'humans', 'important', 'in', 'is', 'it', 'just', 'life', 'make', 'more', 'related', 'science', 'simplify', 'sleeping', 'strongly', 'technology', 'than', 'there', 'things', 'to', 'too', 'what', 'you']
<class 'scipy.sparse.csr.csr_matrix'>
(4, 27)
  (0, 0)	2
  (0, 1)	1
  (0, 6)	1
  (0, 7)	1
  (0, 11)	1
  (0, 14)	1
  (0, 15)	1
  (0, 18)	1
  (0, 19)	1
  (0, 22)	2
  (0, 24)	1
[[2 1 0 0 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 0 0 2 0 1 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0]
 [1 0 0 1 0 0 0 0 1 0 1 1 0 1 0 0 0 1 0 0 1 1 0 1 0 0 0]
 [0 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1]]


# Bag of words using Bi-gram

In [50]:
count_vect = CountVectorizer(ngram_range=(1, 2))
count_vect.fit(text_array)
print("some feature names ", count_vect.get_feature_names())
print('='*50)
final_counts = count_vect.transform(text_array)
print(type(final_counts))
print(final_counts.shape)
print(final_counts[0])
print(final_counts.toarray())

some feature names  ['and', 'and important', 'and sleeping', 'and technology', 'are', 'are strongly', 'be', 'eating', 'eating and', 'enables', 'enables humans', 'humans', 'humans to', 'important', 'important things', 'in', 'in life', 'is', 'is more', 'is what', 'it', 'it to', 'just', 'just eating', 'life', 'life is', 'life than', 'make', 'make it', 'more', 'more to', 'related', 'related things', 'science', 'science and', 'simplify', 'simplify life', 'sleeping', 'strongly', 'strongly related', 'technology', 'technology are', 'technology enables', 'than', 'than just', 'there', 'there is', 'things', 'things and', 'things too', 'to', 'to be', 'to life', 'to simplify', 'too', 'too in', 'what', 'what you', 'you', 'you make']
<class 'scipy.sparse.csr.csr_matrix'>
(4, 60)
  (0, 0)	2
  (0, 1)	1
  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
  (0, 13)	1
  (0, 14)	1
  (0, 15)	1
  (0, 16)	1
  (0, 24)	1
  (0, 31)	1
  (0, 32)	1
  (0, 33)	1
  (0, 34)	1
  (0, 38)	1
  (0, 39)	1
  (0, 40)	1
  (0, 41)	1
  (0, 47)	2
  

# TF-IDF using Bi_gram

In [51]:
tf_idf_vect = TfidfVectorizer(ngram_range=(1,2))
tf_idf_vect.fit(text_array)
print("some sample features(unique words in the corpus)",tf_idf_vect.get_feature_names())

index_list= []
for i in range(len(tf_idf_vect.get_feature_names())):
    index_list.append(i)
zipped_words = zip(index_list,tf_idf_vect.get_feature_names())

for i in zipped_words:
    print(i)
    
print('='*50)

final_tf_idf = tf_idf_vect.transform(text_array)
print("the type of count vectorizer ",type(final_tf_idf))
print("the shape of out text TFIDF vectorizer ",final_tf_idf.get_shape())
print(final_tf_idf[3])
print(final_tf_idf.toarray())

some sample features(unique words in the corpus) ['and', 'and important', 'and sleeping', 'and technology', 'are', 'are strongly', 'be', 'eating', 'eating and', 'enables', 'enables humans', 'humans', 'humans to', 'important', 'important things', 'in', 'in life', 'is', 'is more', 'is what', 'it', 'it to', 'just', 'just eating', 'life', 'life is', 'life than', 'make', 'make it', 'more', 'more to', 'related', 'related things', 'science', 'science and', 'simplify', 'simplify life', 'sleeping', 'strongly', 'strongly related', 'technology', 'technology are', 'technology enables', 'than', 'than just', 'there', 'there is', 'things', 'things and', 'things too', 'to', 'to be', 'to life', 'to simplify', 'too', 'too in', 'what', 'what you', 'you', 'you make']
(0, 'and')
(1, 'and important')
(2, 'and sleeping')
(3, 'and technology')
(4, 'are')
(5, 'are strongly')
(6, 'be')
(7, 'eating')
(8, 'eating and')
(9, 'enables')
(10, 'enables humans')
(11, 'humans')
(12, 'humans to')
(13, 'important')
(14, '

# cosine similarity

In [64]:
test_doc = 'science and technology are important for life'
text_array.append(test_doc)
tf_idf_vect2 = TfidfVectorizer(ngram_range=(1,2))
test_tf_idf = tf_idf_vect2.fit_transform(text_array)
print(test_tf_idf.shape)
print(text_array)
print(cosine_similarity(test_tf_idf[4],test_tf_idf[1]))


(14, 64)
['science and technology are strongly related things and important things too in life', 'Technology enables humans to simplify life', 'there is more to life than just eating and sleeping', 'life is what you make it to be', 'science and technology are important for life', 'science and technology are important for life', 'science and technology are important for life', 'science and technology are important for life', 'science and technology are important for life', 'science and technology are important for life', 'science and technology are important for life', 'science and technology are important for life', 'science and technology are important for life', 'science and technology are important for life']
[[0.05831701]]


In [65]:
text_array = []
string_1 = 'science and technology are strongly related things and important things too in life'
string_2 = 'Technology enables humans to simplify life'
string_3 = 'there is more to life than just eating and sleeping'
string_4 = 'life is what you make it to be'
text_array.append(string_1)
text_array.append(string_2)
text_array.append(string_3)
text_array.append(string_4)
print(text_array)

['science and technology are strongly related things and important things too in life', 'Technology enables humans to simplify life', 'there is more to life than just eating and sleeping', 'life is what you make it to be']


In [75]:
#CV
count_vect_new = CountVectorizer()
cv_fit = count_vect_new.fit_transform(text_array).todense()
print(cv_fit.shape)
print(cv_fit[0])

(4, 27)
[[2 1 0 0 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 0 0 2 0 1 0 0]]


In [86]:
test_doc = 'I am a disco dancer ta ta ta da'
x = count_vect_new.transform([test_doc]).todense()
print(x.shape)
print(x[0])
print(cv_fit[0])
print(cosine_similarity(x[0],cv_fit[0]))

(1, 27)
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[2 1 0 0 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 0 0 2 0 1 0 0]]
[[0.]]
